import Navbar from './components/Navbar'
import { MyProvider } from './context/AppContext'
import './globals.css'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Helpdesk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <MyProvider>
    <html lang="en">
      <body className={rubik.className}>
        {children}
      </body>
    </html>
    </MyProvider>
  )
}
